<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/bootstrap.php';
$user = require_auth();
$pageTitle = 'User Management';
$canManageUsers = $user['role'] === 'SYSTEM ADMINISTRATOR';
require dirname(__DIR__) . '/views/layout/header.php';
?>
<div class="page-heading"><div><div class="eyebrow">ADMINISTRATION</div><h1 class="h3 mb-1">User management</h1><p class="text-secondary mb-0">Manage DPPMS accounts, roles, and access status.</p></div><?php if ($canManageUsers): ?><button class="btn btn-primary" id="add-user">Add user</button><?php endif; ?></div>
<div id="users-alert" class="alert d-none" role="alert"></div>
<section class="card"><div class="card-body p-0"><div class="table-responsive"><table id="users-table" class="table table-hover align-middle mb-0"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Last login</th><?php if ($canManageUsers): ?><th class="text-end">Actions</th><?php endif; ?></tr></thead><tbody></tbody></table></div></div></section>
<div class="modal fade" id="user-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="user-form"><div class="modal-header"><h2 class="modal-title fs-5" id="user-modal-title">Add user</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id"><div class="mb-3"><label class="form-label">Username</label><input class="form-control" name="username" maxlength="80" required></div><div class="mb-3"><label class="form-label">Full name</label><input class="form-control" name="full_name" maxlength="160" required></div><div class="mb-3"><label class="form-label">Email</label><input class="form-control" name="email" type="email" maxlength="190" required></div><div class="mb-3"><label class="form-label">Role</label><select class="form-select" name="role" required><?php foreach (USER_ROLES as $role): ?><option value="<?= e($role) ?>"><?= e($role) ?></option><?php endforeach; ?></select></div><div class="mb-3" id="user-status-wrap"><label class="form-label">Status</label><select class="form-select" name="status"><option>ACTIVE</option><option>INACTIVE</option></select></div><div class="mb-3" id="user-password-wrap"><label class="form-label">Temporary password</label><input class="form-control" name="password" type="password" autocomplete="new-password"><div class="form-text">Required for new users. Leave blank when editing to keep the current password.</div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Save user</button></div></form></div></div></div>
<?php require dirname(__DIR__) . '/views/layout/footer.php'; ?>
