CREATE TABLE projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_code VARCHAR(40) NOT NULL,
    project_name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    project_owner_id BIGINT UNSIGNED NOT NULL,
    department_requestor VARCHAR(190) NULL,
    priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    start_date DATE NULL,
    target_date DATE NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PLANNING',
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_projects_project_code (project_code),
    KEY idx_projects_status (status),
    KEY idx_projects_owner (project_owner_id),
    KEY idx_projects_priority (priority),
    KEY idx_projects_target_date (target_date),
    KEY idx_projects_created_by (created_by),
    CONSTRAINT fk_projects_owner FOREIGN KEY (project_owner_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_projects_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    CONSTRAINT chk_projects_status CHECK (status IN ('PLANNING', 'ACTIVE', 'ON HOLD', 'FOR TESTING', 'FOR DEPLOYMENT', 'COMPLETED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
