CREATE TABLE tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    task_code VARCHAR(100) NOT NULL,
    task_title VARCHAR(200) NOT NULL,
    description TEXT NULL,
    assigned_to BIGINT UNSIGNED NULL,
    priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    status VARCHAR(24) NOT NULL DEFAULT 'BACKLOG',
    start_date DATE NULL,
    target_date DATE NULL,
    completed_at DATETIME NULL,
    estimated_hours DECIMAL(9,2) NULL,
    actual_hours DECIMAL(9,2) NULL,
    is_blocked TINYINT(1) NOT NULL DEFAULT 0,
    blocked_reason TEXT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tasks_task_code (task_code),
    KEY idx_tasks_project (project_id),
    KEY idx_tasks_assigned_to (assigned_to),
    KEY idx_tasks_status (status),
    KEY idx_tasks_priority (priority),
    KEY idx_tasks_target_date (target_date),
    KEY idx_tasks_project_status (project_id, status),
    KEY idx_tasks_created_by (created_by),
    CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_tasks_assigned_to FOREIGN KEY (assigned_to) REFERENCES users (id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_tasks_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_tasks_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
    CONSTRAINT chk_tasks_status CHECK (status IN ('BACKLOG', 'TO DO', 'IN PROGRESS', 'FOR TESTING', 'FOR REVISION', 'FOR DEPLOYMENT', 'COMPLETED')),
    CONSTRAINT chk_tasks_blocked CHECK (is_blocked IN (0, 1)),
    CONSTRAINT chk_tasks_estimated_hours CHECK (estimated_hours IS NULL OR estimated_hours >= 0),
    CONSTRAINT chk_tasks_actual_hours CHECK (actual_hours IS NULL OR actual_hours >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
