ALTER TABLE tasks
    DROP CONSTRAINT chk_tasks_status,
    ADD CONSTRAINT chk_tasks_status CHECK (status IN ('BACKLOG', 'TO DO', 'IN PROGRESS', 'FOR TESTING', 'FOR REVISION', 'FOR DEPLOYMENT', 'COMPLETED', 'CANCELLED'));
